# DS4400 HW1

In [7]:
import numpy as np
import matplotlib.pyplot as plt 

import pandas as pd  
import seaborn as sns 

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV

## Problem 4

### Part C

In [3]:
# genrate 3 random 3x3 matrices with integers from -10 to 10
matrices = []
for i in range(3):
    M = np.random.randint(-10, 11, size=(3, 3))
    matrices.append(M)

In [8]:
 # print each matrix out
for i, M in enumerate(matrices):
    print(f"Matrix {i+1}:")
    print(M)
    
    # compute determinant to determine if invertible
    det = np.linalg.det(M)
    print(f"Determinant: {np.round(det, 4)}")
    
    if abs(det) < 0.000001:
        print("Matrix is singular so it is not invertible")
        
    else:
        # compute inverse using Numpy
        M_inv = np.linalg.inv(M)
        print(f"\nInverse of Matrix {i+1}:")
        print(np.round(M_inv, 4))
        
        # M * M_inverse should equal Identity
        product = M @ M_inv
        print(f"\nVerification of Identity:")
        print(np.round(product, 4))
        print()

Matrix 1:
[[-10  -2   4]
 [ -5  -5  -6]
 [  3  -1   5]]
Determinant: 376.0

Inverse of Matrix 1:
[[-0.0824  0.016   0.0851]
 [ 0.0186 -0.1649 -0.2128]
 [ 0.0532 -0.0426  0.1064]]

Verification of Identity:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]

Matrix 2:
[[ -1  -6 -10]
 [  3   5  -7]
 [-10   9   3]]
Determinant: -1214.0

Inverse of Matrix 2:
[[-0.0643  0.0593 -0.0758]
 [-0.0502  0.0848  0.0305]
 [-0.0634 -0.0568 -0.0107]]

Verification of Identity:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]

Matrix 3:
[[-9 -6 -7]
 [-1  1  4]
 [ 3  2 -2]]
Determinant: 65.0

Inverse of Matrix 3:
[[-0.1538 -0.4    -0.2615]
 [ 0.1538  0.6     0.6615]
 [-0.0769 -0.     -0.2308]]

Verification of Identity:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



## Problem 5

In [10]:
df = pd.read_csv('kc_house_data.csv')

In [13]:
# remove columns to ignore: id, date, zipcode
cols_to_drop = ['id', 'date', 'zipcode']
df_clean = df.drop(columns=cols_to_drop)
#df_clean.head()

### Part A

In [16]:
# seperate features and exclude price
house_data = df_clean.drop(columns=['price'])

# stats for each feature
stats = pd.DataFrame({
    'Average': house_data.mean(),
    'Min': house_data.min(),
    'Max': house_data.max(),
    'Variance': house_data.var()
})
stats

,Average,Min,Max,Variance
bedrooms,3.370842,0.0000,3.300000e+01,8.650150e-01
bathrooms,2.114757,0.0000,8.000000e+00,5.931513e-01
sqft_living,2079.899736,290.0000,1.354000e+04,8.435337e+05
sqft_lot,15106.967566,520.0000,1.651359e+06,1.715659e+09
floors,1.494309,1.0000,3.500000e+00,2.915880e-01
waterfront,0.007542,0.0000,1.000000e+00,7.485226e-03
view,0.234303,0.0000,4.000000e+00,5.872426e-01
condition,3.409430,1.0000,5.000000e+00,4.234665e-01
grade,7.656873,1.0000,1.300000e+01,1.381703e+00
sqft_above,1788.390691,290.0000,9.410000e+03,6.857347e+05


In [21]:
# features with lowest and highest average
lowest_avg = stats['Average'].idxmin()
highest_avg = stats['Average'].idxmax()

print(f"Lowest average:  {lowest_avg} = {stats.loc[lowest_avg, 'Average']:.4f}")
print(f"Highest average: {highest_avg} = {stats.loc[highest_avg, 'Average']:.4f}")

Lowest average:  long = -122.2139
Highest average: sqft_lot = 15106.9676


In [22]:
# features with lowest and highest variance
lowest_var = stats['Variance'].idxmin()
highest_var = stats['Variance'].idxmax()

print(f"Lowest variance:  {lowest_var} = {stats.loc[lowest_var, 'Variance']:.4f}")
print(f"Highest variance: {highest_var} = {stats.loc[highest_var, 'Variance']:.4f}")

Lowest variance:  waterfront = 0.0075
Highest variance: sqft_lot = 1715658774.1755


### Part B

In [27]:
# correlation of each feature w/ price
correlations = features.apply(lambda x: x.corr(df_clean['price']))
corr_table = pd.DataFrame({
    'Feature': correlations.index,
    'Correlation with Price': correlations.values
}).sort_values(by='Correlation with Price', ascending=False)

print(corr_table.to_string(index=False))

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


Every correlation coefficient is positive, indicating a positive correlation with the price for each feature.

In [30]:
# feature with highest positive correlation
highest_corr_feature = corr_table.iloc[0]
print(f"\nHighest positive correlation: {highest_corr_feature['Feature']} = {highest_corr_feature['Correlation with Price']:.4f}")


Highest positive correlation: sqft_living = 0.7020


### Part C

In [31]:
negative_corr = corr_table[corr_table['Correlation with Price'] < 0]

if len(negative_corr) > 0:
    print("The following features have negative correlation with price:")
    print(negative_corr)
else:
    print("No features have negative correlation with price.")

No features have negative correlation with price.
